//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BilklPaymentWenFormPortal.Api {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BillPaymentApiEndPointSoap", Namespace="http://tempuri.org/")]
    public partial class BillPaymentApiEndPoint : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateUtilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateVendorOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BillPaymentApiEndPoint() {
            this.Url = global::BilklPaymentWenFormPortal.Properties.Settings.Default.BilklPaymentWenFormPortal_BillPaymentApi_BillPaymentApiEndPoint;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateUserCompletedEventHandler CreateUserCompleted;
        
        /// <remarks/>
        public event CreateCustomerCompletedEventHandler CreateCustomerCompleted;
        
        /// <remarks/>
        public event CreateUtilityCompletedEventHandler CreateUtilityCompleted;
        
        /// <remarks/>
        public event CreateVendorCompletedEventHandler CreateVendorCompleted;
        
        /// <remarks/>
        public event LoginUserCompletedEventHandler LoginUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseOfInt32 CreateUser(string ReferenceNumber, string CustomerName, string phoneNumer, string UtilityCodse, int CreatedBy) {
            object[] results = this.Invoke("CreateUser", new object[] {
                        ReferenceNumber,
                        CustomerName,
                        phoneNumer,
                        UtilityCodse,
                        CreatedBy});
            return ((ApiResponseOfInt32)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUserAsync(string ReferenceNumber, string CustomerName, string phoneNumer, string UtilityCodse, int CreatedBy) {
            this.CreateUserAsync(ReferenceNumber, CustomerName, phoneNumer, UtilityCodse, CreatedBy, null);
        }
        
        /// <remarks/>
        public void CreateUserAsync(string ReferenceNumber, string CustomerName, string phoneNumer, string UtilityCodse, int CreatedBy, object userState) {
            if ((this.CreateUserOperationCompleted == null)) {
                this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
            }
            this.InvokeAsync("CreateUser", new object[] {
                        ReferenceNumber,
                        CustomerName,
                        phoneNumer,
                        UtilityCodse,
                        CreatedBy}, this.CreateUserOperationCompleted, userState);
        }
        
        private void OnCreateUserOperationCompleted(object arg) {
            if ((this.CreateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseOfInt32 CreateCustomer(string ReferenceNumber, string CustomerName, string email, string phoneNumer, string password, string UtilityCodse, int CreatedBy) {
            object[] results = this.Invoke("CreateCustomer", new object[] {
                        ReferenceNumber,
                        CustomerName,
                        email,
                        phoneNumer,
                        password,
                        UtilityCodse,
                        CreatedBy});
            return ((ApiResponseOfInt32)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCustomerAsync(string ReferenceNumber, string CustomerName, string email, string phoneNumer, string password, string UtilityCodse, int CreatedBy) {
            this.CreateCustomerAsync(ReferenceNumber, CustomerName, email, phoneNumer, password, UtilityCodse, CreatedBy, null);
        }
        
        /// <remarks/>
        public void CreateCustomerAsync(string ReferenceNumber, string CustomerName, string email, string phoneNumer, string password, string UtilityCodse, int CreatedBy, object userState) {
            if ((this.CreateCustomerOperationCompleted == null)) {
                this.CreateCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCustomerOperationCompleted);
            }
            this.InvokeAsync("CreateCustomer", new object[] {
                        ReferenceNumber,
                        CustomerName,
                        email,
                        phoneNumer,
                        password,
                        UtilityCodse,
                        CreatedBy}, this.CreateCustomerOperationCompleted, userState);
        }
        
        private void OnCreateCustomerOperationCompleted(object arg) {
            if ((this.CreateCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCustomerCompleted(this, new CreateCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateUtility", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseOfInt32 CreateUtility(string UtilityName, string UtilityCode, int CreatedBy) {
            object[] results = this.Invoke("CreateUtility", new object[] {
                        UtilityName,
                        UtilityCode,
                        CreatedBy});
            return ((ApiResponseOfInt32)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUtilityAsync(string UtilityName, string UtilityCode, int CreatedBy) {
            this.CreateUtilityAsync(UtilityName, UtilityCode, CreatedBy, null);
        }
        
        /// <remarks/>
        public void CreateUtilityAsync(string UtilityName, string UtilityCode, int CreatedBy, object userState) {
            if ((this.CreateUtilityOperationCompleted == null)) {
                this.CreateUtilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUtilityOperationCompleted);
            }
            this.InvokeAsync("CreateUtility", new object[] {
                        UtilityName,
                        UtilityCode,
                        CreatedBy}, this.CreateUtilityOperationCompleted, userState);
        }
        
        private void OnCreateUtilityOperationCompleted(object arg) {
            if ((this.CreateUtilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUtilityCompleted(this, new CreateUtilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateVendor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseOfInt32 CreateVendor(string vendorCode, string vendorName, string conatactEmail, string conatatPhone, string password, decimal balance, int createdBy) {
            object[] results = this.Invoke("CreateVendor", new object[] {
                        vendorCode,
                        vendorName,
                        conatactEmail,
                        conatatPhone,
                        password,
                        balance,
                        createdBy});
            return ((ApiResponseOfInt32)(results[0]));
        }
        
        /// <remarks/>
        public void CreateVendorAsync(string vendorCode, string vendorName, string conatactEmail, string conatatPhone, string password, decimal balance, int createdBy) {
            this.CreateVendorAsync(vendorCode, vendorName, conatactEmail, conatatPhone, password, balance, createdBy, null);
        }
        
        /// <remarks/>
        public void CreateVendorAsync(string vendorCode, string vendorName, string conatactEmail, string conatatPhone, string password, decimal balance, int createdBy, object userState) {
            if ((this.CreateVendorOperationCompleted == null)) {
                this.CreateVendorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateVendorOperationCompleted);
            }
            this.InvokeAsync("CreateVendor", new object[] {
                        vendorCode,
                        vendorName,
                        conatactEmail,
                        conatatPhone,
                        password,
                        balance,
                        createdBy}, this.CreateVendorOperationCompleted, userState);
        }
        
        private void OnCreateVendorOperationCompleted(object arg) {
            if ((this.CreateVendorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateVendorCompleted(this, new CreateVendorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseOfInt32 LoginUser(string username, string password) {
            object[] results = this.Invoke("LoginUser", new object[] {
                        username,
                        password});
            return ((ApiResponseOfInt32)(results[0]));
        }
        
        /// <remarks/>
        public void LoginUserAsync(string username, string password) {
            this.LoginUserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginUserAsync(string username, string password, object userState) {
            if ((this.LoginUserOperationCompleted == null)) {
                this.LoginUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginUserOperationCompleted);
            }
            this.InvokeAsync("LoginUser", new object[] {
                        username,
                        password}, this.LoginUserOperationCompleted, userState);
        }
        
        private void OnLoginUserOperationCompleted(object arg) {
            if ((this.LoginUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginUserCompleted(this, new LoginUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApiResponseOfInt32 {
        
        private bool successField;
        
        private string messageField;
        
        private int dataField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateUserCompletedEventHandler(object sender, CreateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseOfInt32 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseOfInt32)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateCustomerCompletedEventHandler(object sender, CreateCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseOfInt32 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseOfInt32)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateUtilityCompletedEventHandler(object sender, CreateUtilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUtilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUtilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseOfInt32 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseOfInt32)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateVendorCompletedEventHandler(object sender, CreateVendorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateVendorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateVendorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseOfInt32 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseOfInt32)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void LoginUserCompletedEventHandler(object sender, LoginUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseOfInt32 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseOfInt32)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591